version: '2.1'

services:
  streaming-binlog: 
    #TO DO : needs to be moved to openmrs repo
    image:  mozzy11/openmrs-fhir-analytics-streaming-binlog:v1
    container_name: streaming-pipeline
    network_mode: host
    healthcheck:
      test: "exit 0"
    volumes:
      - ./volumes/dbz_event_to_fhir_config.json:/deployments/dbz_event_to_fhir_config.json
    environment:
      - OPENMRS_URL=http://localhost:8080/openmrs
      - OPENMRS_USERNAME=admin
      - OPENMRS_PASSWORD=Admin123
      - SINK_URL=http://localhost:5001/fhir
      - SINK_USERNAME=hapi
      - SINK_PASSWORD=Admin123
      - JDBC_FETCH_SIZE=10000
      - JDBC_MAX_POOL_SIZE=50
      - JDBC_INITIAL_POOL_SIZE=10
      - JDBC_URL=jdbc:mysql://localhost:3306/openmrs
      - JDBC_DRIVER_CLASS=com.mysql.cj.jdbc.Driver
      - FHIR_DEBEZIUM_CONFIG_PATH=/deployments/dbz_event_to_fhir_config.json